# Generated by Django 4.0.6 on 2022-07-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created',), 'verbose_name_plural': 'products'},
        ),
    ]
