# Generated by Django 4.0.6 on 2022-07-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_creator_product_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='images/%Y/%m/%d/'),
        ),
    ]
