# Generated by Django 4.0.6 on 2022-07-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default-image.jpg', upload_to='images/%Y/%m/%d/'),
        ),
    ]
